#!/bin/bash
dpkg-deb -bZgzip projects/buuf1 debs
dpkg-deb -bZgzip projects/buuf2 debs
dpkg-deb -bZgzip projects/buuf3 debs
dpkg-deb -bZgzip projects/buuf4 debs
dpkg-deb -bZgzip projects/buuf5 debs
dpkg-deb -bZgzip projects/buuf6 debs
dpkg-deb -bZgzip projects/essenza70rev debs
dpkg-deb -bZgzip projects/essenza162 debs
dpkg-deb -bZgzip projects/buuf7 debs
dpkg-deb -bZgzip projects/essenza163 debs
dpkg-deb -bZgzip projects/essenza164 debs
dpkg-deb -bZgzip projects/essenza165 debs
dpkg-deb -bZgzip projects/dubsIS2e166 debs
dpkg-deb -bZgzip projects/dubsIS2e167TouchForecast debs
dpkg-deb -bZgzip projects/dubsIS2e168TouchForecast debs
dpkg-deb -bZgzip projects/dubsIS2buuf8 debs
dpkg-deb -bZgzip projects/dubsIS2e169TouchForecast debs
dpkg-deb -bZgzip projects/dubsIS2buuf9 debs
dpkg-deb -bZgzip projects/dubsIS2buuf10-LS debs
dpkg-deb -bZgzip projects/essenza170 debs
dpkg-deb -bZgzip projects/essenza171 debs
dpkg-deb -bZgzip projects/essenza172 debs
dpkg-deb -bZgzip projects/essenza173 debs
dpkg-deb -bZgzip projects/essenza174 debs
dpkg-deb -bZgzip projects/essenza175 debs
dpkg-deb -bZgzip projects/dubsIS2buuf11 debs
dpkg-deb -bZgzip projects/dubsIS2buuf12 debs
dpkg-deb -bZgzip projects/dubsIS2buuf13 debs
dpkg-deb -bZgzip projects/dubsIS2buuf13-LS debs
dpkg-deb -bZgzip projects/dubsIS2buuf14-iW debs
dpkg-deb -bZgzip projects/dubsIS2buuf15-SBHTML-BadGirl debs
dpkg-deb -bZgzip projects/dubsIS2buuf15-SBHTML-deadpool debs
dpkg-deb -bZgzip projects/dubsIS2buuf16-SBHTML-armmaggedon debs
dpkg-deb -bZgzip projects/dubsIS2buuf17-SBHTML-evelyn debs
dpkg-deb -bZgzip projects/dubsIS2buuf18-SBHTML-pirates debs
dpkg-deb -bZgzip projects/dubsIS2buuf19-iW-captainamerica debs
dpkg-deb -bZgzip projects/dubsbuuf20-iW-hulk debs
dpkg-deb -bZgzip projects/dubsbuuf20A-iW-batman debs
dpkg-deb -bZgzip projects/dubsbuuf21-iW-supermario debs
dpkg-deb -bZgzip projects/dubsbuuf22-iW-harley debs
dpkg-deb -bZgzip projects/dubsIS2elixirSBHTML1  debs
dpkg-deb -bZgzip projects/dubsIS2elixiriW1 debs
dpkg-deb -bZgzip projects/dubsIS2elixiriW2 debs
