#!/bin/bash
dpkg-deb -bZgzip projects/buuf1 debs
dpkg-deb -bZgzip projects/buuf2 debs
dpkg-deb -bZgzip projects/buuf3 debs
dpkg-deb -bZgzip projects/buuf4 debs
dpkg-deb -bZgzip projects/buuf5 debs
dpkg-deb -bZgzip projects/buuf6 debs
dpkg-deb -bZgzip projects/essenza70rev debs
dpkg-deb -bZgzip projects/essenza162 debs
dpkg-deb -bZgzip projects/buuf7 debs
dpkg-deb -bZgzip projects/essenza163 debs
dpkg-deb -bZgzip projects/essenza164 debs
dpkg-deb -bZgzip projects/essenza165 debs
dpkg-deb -bZgzip projects/dubsIS2e166 debs
dpkg-deb -bZgzip projects/dubsIS2e167TouchForecast debs
dpkg-deb -bZgzip projects/dubsIS2e168TouchForecast debs
dpkg-deb -bZgzip projects/dubsIS2buuf8 debs
dpkg-deb -bZgzip projects/dubsIS2e169TouchForecast debs
dpkg-deb -bZgzip projects/dubsIS2buuf9 debs
dpkg-deb -bZgzip projects/dubsIS2buuf10-LS debs
